# -*- Mode: Python; tab-width: 4; c-basic-offset: 4 -*-
srcdir = '.'
blddir = 'build'
VERSION = '0.0.1'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	conf.check_tool('compiler_cxx')
	conf.check_tool('node_addon')
	conf.define('_GNU_SOURCE', 1)
	conf.define('_XOPEN_REALTIME', 1)
	conf.check_cxx(function_name = 'posix_fadvise', header_name = "fcntl.h", mandatory = False)
	conf.check_cxx(function_name = 'posix_fallocate', header_name = "fcntl.h", mandatory = False)
	conf.check_cxx(function_name = 'fallocate', header_name = "fcntl.h", mandatory = False)
	conf.write_config_header('config.h')

def build(bld):
	obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
	obj.target = 'native_support'
	obj.source = 'native_support.cpp'
